/**
 * Codegen (ADR 0005): turn a Schema into a typed client via string templates.
 * Emits per-Type interfaces, `*Input` (writeable) and `*Populated` variants, a
 * runtime `schema` object, and the `createClient(adapter)` factory.
 */

import type { Field, Schema, Type } from '../model/schema';
import { camelCase, pascalCase } from './naming';

const PKG = '@usc/zero-cms-core';

function quote(s: string): string {
  return JSON.stringify(s);
}

/** TS type for a field's base (unpopulated) value. */
function baseFieldType(field: Field): string {
  switch (field.__type) {
    case 'text':
    case 'longtext':
    case 'richtext':
    case 'asset':
      return 'string';
    case 'number':
      return 'number';
    case 'blocks':
      return 'BlocksContent';
    case 'json':
      return 'JsonValue';
    case 'boolean':
      return 'boolean';
    case 'lookup':
      return field.options.length
        ? field.options.map(quote).join(' | ')
        : 'string';
    case 'reference':
      return 'string';
    case 'references':
      return 'string[]';
  }
}

/** TS type for a field when populated (references become nested entities). */
function populatedFieldType(field: Field): string {
  if (field.__type === 'reference')
    return `${refUnion(field.allowedTypes)} | null`;
  if (field.__type === 'references')
    return `Array<${refUnion(field.allowedTypes)}>`;
  return baseFieldType(field);
}

function refUnion(allowed: string[]): string {
  return allowed.length ? allowed.map((t) => pascalCase(t)).join(' | ') : 'unknown';
}

function optional(field: Field): string {
  return field.required ? '' : '?';
}

function entityInterface(type: Type): string {
  const name = pascalCase(type.__name);
  const meta = [
    `  __id: string;`,
    `  __type: ${quote(type.__name)};`,
    `  __status: 'published' | 'unpublished';`,
    `  hasDraft: boolean;`,
  ].join('\n');
  const fields = type.fields
    .map((f) => `  ${f.__name}${optional(f)}: ${baseFieldType(f)};`)
    .join('\n');
  return `export interface ${name} {\n${meta}\n${fields}\n}`;
}

function inputInterface(type: Type): string {
  const name = `${pascalCase(type.__name)}Input`;
  const fields = type.fields
    .map((f) => `  ${f.__name}${optional(f)}: ${baseFieldType(f)};`)
    .join('\n');
  return `export interface ${name} {\n${fields}\n}`;
}

function populatedInterface(type: Type): string {
  const base = pascalCase(type.__name);
  const refFields = type.fields.filter(
    (f) => f.__type === 'reference' || f.__type === 'references'
  );
  if (refFields.length === 0)
    return `export type ${base}Populated = ${base};`;
  const overrides = refFields
    .map((f) => `  ${f.__name}${optional(f)}: ${populatedFieldType(f)};`)
    .join('\n');
  const omit = refFields.map((f) => quote(f.__name)).join(' | ');
  return `export interface ${base}Populated extends Omit<${base}, ${omit}> {\n${overrides}\n}`;
}

export function generateClientSource(schema: Schema): string {
  const interfaces = schema
    .map(
      (t) =>
        `${entityInterface(t)}\n\n${inputInterface(t)}\n\n${populatedInterface(t)}`
    )
    .join('\n\n');

  const stores = schema
    .map((t) => {
      const entity = pascalCase(t.__name);
      return `    ${camelCase(t.__name)}Store: bindStore<${entity}Input, ${entity}>(adapter, ${quote(
        t.__name
      )}),`;
    })
    .join('\n');

  return `/* eslint-disable */
/**
 * AUTO-GENERATED by zero-cms-core. Do not edit by hand.
 * Regenerated from types.json on schema change.
 */
import type { Adapter, Schema, BlocksContent, JsonValue } from ${quote(PKG)};
import { bindStore } from ${quote(PKG)};

${interfaces}

export const schema: Schema = ${JSON.stringify(schema, null, 2)};

export function createClient(adapter: Adapter) {
  return {
${stores}
  };
}

export type ZeroCmsClient = ReturnType<typeof createClient>;
`;
}
